version: "3"

networks:
  laravel:
    driver: bridge

services:
  hp-nginx:
    image: nginx:stable
    container_name: hp-nginx
    platform: linux/amd64
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/app:delegated
    depends_on:
      - hp-php-fpm
    extra_hosts:
      - hp-api.local:127.0.0.1
    networks:
      - laravel

  hp-php-fpm:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: hp-php-fpm
    platform: linux/amd64
    restart: unless-stopped
    tty: true
    expose:
      - "9000"
    depends_on:
      - hp-redis
      - hp-mysql
    volumes:
      - .:/var/www/app:delegated
    networks:
      - laravel

  hp-mysql:
    image: mysql:8.0
    container_name: hp-mysql
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DEFAULT_AUTH='mysql_native_password'
    ports:
        - "3306:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - ./docker/mysql/dbdata:/var/lib/mysql
    networks:
      - laravel

  hp-redis:
    image: redis:latest
    container_name: hp-redis
    platform: linux/amd64
    ports:
      - "6379:6379"
    networks:
      - laravel